src/main/java/com/book/backend/domain/user/entity/Sex.java
src/main/java/com/book/backend/domain/user/entity/User.java
src/main/java/com/book/backend/domain/user/repository/UserRepository.java
src/main/java/com/book/backend/domain/user/service/UserService.java

[feat] 회원 엔티티, 레포지토리, 서비스 클래스 생성

---

.github/workflows/main.yml
Dockerfile
build.gradle
docker-compose.yml
src/main/java/com/book/backend/global/SwaggerConfig.java
src/main/resources/application.yml
src/test/java/com/book/backend/BackendApplicationTests.java

#4 
issue 4 참고
> DB URL 을 분리함에 따라 .env 파일 일부가 수정되었습니다. notion 을 참고해주세요

#4 setting

---

src/main/java/com/book/backend/domain/auth/service/CustomUserDetailsService.java
src/main/java/com/book/backend/exception/CustomException.java
src/main/java/com/book/backend/exception/ErrorCode.java
src/main/java/com/book/backend/global/SecurityConfig.java

#6
- 커스텀 에러 클래스 생성
- 회원 권한 설정
- Spring Security 설정
현재는 `CustomUserDetailsService`에서 회원 권한을 `ROLE_USER`로만 지정하고 있으나, 추후 admin 등 다른 권한이 필요하면 그에 맞게끔 수정 가능합니다.
또한 `SecurityConfig`를 통해, 임시적으로 모든 페이지에 대한 접근 권한을 해제하도록 수정했습니다.

#6 spring security

---

.github/ISSUE_TEMPLATE/feature-template.md
.github/workflows/main.yml
Dockerfile
build.gradle
docker-compose.yml
src/main/java/com/book/backend/domain/auth/service/CustomUserDetailsService.java
src/main/java/com/book/backend/exception/CustomException.java
src/main/java/com/book/backend/exception/ErrorCode.java
src/main/java/com/book/backend/global/SecurityConfig.java
src/main/java/com/book/backend/global/SwaggerConfig.java
src/main/resources/application.yml
src/test/java/com/book/backend/BackendApplicationTests.java

[refactor] feature-template.md title 변경

---

src/main/resources/application.yml
src/main/resources/data.sql

#20 data.sql

---

src/main/java/com/book/backend/domain/book/controller/BookController.java
src/main/java/com/book/backend/domain/book/dto/TestDto.java
src/main/java/com/book/backend/domain/book/service/BookService.java
src/main/java/com/book/backend/global/WebConfig.java
src/main/java/com/book/backend/global/log/LogBackConfig.java
src/main/java/com/book/backend/global/log/LoggingInterceptor.java
src/main/java/com/book/backend/global/log/RequestLogger.java

성공시👇
에러 발생시👇
로깅 사용법
> 1. **Controller** 에선 request param, body 에 맞는 로그를 찍어주세요
> - param() 의 첫번째 메소드로 변수명을 배열에 담고, 그 뒤로 순서대로 변수를 쭉 인자로 넣으면 됩니다.
> - body() 는 dto 자체를 넘기면 됩니다.
> <img src="https://github.com/user-attachments/assets/9f0262c3-bb18-4435-af89-995782f1fe9d" width=65%>
</br>
> 2. **Service** 에선 진입 로그를 찍어주세요
> - log.trace(메소드명)
> <img src="https://github.com/user-attachments/assets/2f23a93c-2467-41f6-b88f-67b7a5b8e5b9" width=40%>

#23 log custom

---

src/main/java/com/book/backend/domain/book/controller/BookController.java
src/main/java/com/book/backend/domain/openapi/dto/response/CustomHotTrendResponseDto.java
src/main/java/com/book/backend/domain/openapi/dto/response/HotTrendResponseDto.java
src/main/java/com/book/backend/domain/openapi/dto/response/KeywordResponseDto.java
src/main/java/com/book/backend/domain/openapi/dto/response/RecommendResponseDto.java

</br> </br>
request 설명 추가 예시 👇 </br>
> controller 설명, request 설명은 ~controller.java 파일의 각 컨트롤러마다 추가해야하고, 
> response 설명은 ~resopnseDto 마다 description 값을 추가하면 됩니다 !

#36 swagger

---

src/main/java/com/book/backend/domain/auth/controller/AuthController.java
src/main/java/com/book/backend/domain/auth/dto/KakaoTokenResponseDto.java
src/main/java/com/book/backend/domain/auth/dto/KakaoUserInfoDto.java
src/main/java/com/book/backend/domain/auth/service/CustomUserDetailsService.java
src/main/java/com/book/backend/domain/auth/service/KakaoService.java
src/main/java/com/book/backend/domain/user/dto/UserDto.java
src/main/java/com/book/backend/domain/user/entity/User.java
src/main/java/com/book/backend/domain/user/repository/UserRepository.java
src/main/java/com/book/backend/exception/ErrorCode.java
src/main/java/com/book/backend/global/AuthConfig.java
src/main/java/com/book/backend/global/SecurityConfig.java
src/main/resources/application.yml

[카카오 디벨로퍼스 내의 REST API 페이지](https://developers.kakao.com/docs/latest/ko/kakaologin/rest-api#before-you-begin-process)에서 제공하는 시퀀스 다이어그램을 참고하여 필요한 로직을 구현했습니다.
> 1. .env 파일의 내용이 변경되었습니다. 노션을 확인해주세요!
> 2. Authorization code를 parameter로 받아 카카오 로그인이 처리되는 방식입니다.
> 3. kakao 로그인한 유저를 처리하기 위해 User 엔티티의 loginId 필드를 unique 해제했고, kakaoId 필드를 추가했습니다.
> 4. [구현 과정에서 참고한 게시글](https://growth-coder.tistory.com/187)을 공유합니다! 테스트 시 참고해주시면 감사하겠습니다.
> 
> 기타 수정해야 할 부분이 있다면 말씀해주시면 감사하겠습니다!

#41 oauth kakao

---

src/main/java/com/book/backend/domain/auth/controller/AuthController.java
src/main/java/com/book/backend/domain/auth/service/JwtAuthenticationFilter.java
src/main/java/com/book/backend/exception/ErrorCode.java
src/main/java/com/book/backend/exception/ExceptionHandlerResponse.java
src/main/java/com/book/backend/global/CustomAuthenticationEntryPoint.java
src/main/java/com/book/backend/global/ResponseTemplate.java

> API 응답 형식을 수정했습니다. 참고해주세요!
>   - 참고: 기존 ResponseTemplate의 HashMap을 LinkedHashMap으로 수정하여 순서를 지정했습니다.

#54 edit api format

---

build.gradle
src/main/java/com/book/backend/global/SwaggerConfig.java

#56 add swagger header

---

src/main/java/com/book/backend/domain/auth/service/JwtAuthenticationFilter.java
src/main/java/com/book/backend/exception/ErrorCode.java
src/main/java/com/book/backend/global/CustomAuthenticationEntryPoint.java

#54 edit api format 2

---

src/main/java/com/book/backend/domain/genre/controller/GenreController.java
src/main/java/com/book/backend/domain/genre/service/GenreResponseParser.java
src/main/java/com/book/backend/domain/genre/service/GenreService.java

> aWeekTrend, aMonthTrend API에 커스텀 페이지네이션 메서드(customPageFilter)를 적용했습니다!

[refactor] aWeekTrend, aMonthTrend API에 커스텀 페이지네이션 적용

---

src/main/java/com/book/backend/domain/auth/dto/SignupDto.java
src/main/java/com/book/backend/domain/auth/mapper/AuthMapper.java
src/main/java/com/book/backend/domain/user/controller/UserController.java
src/main/java/com/book/backend/domain/user/dto/UserDto.java
src/main/java/com/book/backend/domain/user/dto/UserInfoDto.java
src/main/java/com/book/backend/domain/user/mapper/UserMapper.java
src/main/java/com/book/backend/domain/user/service/UserService.java

> UserService에 있는 loadLoggedinUser 메서드로 현재 로그인된 사용자 객체(User)를 불러올 수 있습니다. 참고해주세요!

#63 user info api

---

src/main/java/com/book/backend/domain/auth/dto/SignupDto.java
src/main/java/com/book/backend/domain/user/dto/UserDto.java
src/main/java/com/book/backend/domain/user/entity/User.java
src/main/java/com/book/backend/domain/user/repository/UserRepository.java
src/main/resources/dummy.sql

[chore] email, phone 필드 제거

---

src/main/java/com/book/backend/domain/auth/controller/AuthController.java
src/main/java/com/book/backend/domain/auth/dto/LoginSuccessResponseDto.java
src/main/java/com/book/backend/domain/auth/service/KakaoService.java

#77 add kakao login dto field

---

src/main/java/com/book/backend/domain/detail/controller/DetailController.java
src/main/java/com/book/backend/domain/detail/dto/LoanAvailableDto.java
src/main/java/com/book/backend/domain/detail/service/DetailService.java
src/main/java/com/book/backend/domain/openapi/dto/response/DetailResponseDto.java
src/main/java/com/book/backend/domain/user/dto/UserLibrariesDto.java
src/main/java/com/book/backend/domain/user/service/UserService.java

> 상세 API는 김민님이 요청하신대로 수정했고, 
> 주변 도서관 edit API 에 libcode validate 코드 추가했습니다!

8/21 수정사항 (책 상세)

---

src/main/java/com/book/backend/domain/book/repository/BookRepository.java
src/main/java/com/book/backend/domain/detail/controller/DetailController.java
src/main/java/com/book/backend/domain/detail/dto/LoanAvailableDto.java
src/main/java/com/book/backend/domain/detail/service/DetailService.java
src/main/java/com/book/backend/domain/openapi/dto/response/DetailResponseDto.java
src/main/java/com/book/backend/domain/openapi/dto/response/SearchResponseDto.java
src/main/java/com/book/backend/domain/opentalk/repository/OpentalkRepository.java
src/main/java/com/book/backend/domain/search/controller/SearchController.java
src/main/java/com/book/backend/domain/search/service/SearchService.java
src/main/java/com/book/backend/domain/user/controller/UserController.java
src/main/java/com/book/backend/domain/user/dto/MyPageDto.java
src/main/java/com/book/backend/domain/user/dto/UserDto.java
src/main/java/com/book/backend/domain/user/entity/User.java
src/main/java/com/book/backend/domain/userBook/controller/UserBookController.java
src/main/java/com/book/backend/domain/userBook/dto/UserBookDto.java
src/main/java/com/book/backend/domain/userBook/service/UserBookService.java
src/main/java/com/book/backend/exception/ErrorCode.java

#84 book dibs

---

src/main/java/com/book/backend/domain/auth/controller/AuthController.java
src/main/java/com/book/backend/domain/auth/service/AuthService.java
src/main/java/com/book/backend/domain/auth/service/CustomUserDetailsService.java
src/main/java/com/book/backend/domain/auth/service/JwtAuthenticationFilter.java
src/main/java/com/book/backend/domain/auth/service/JwtRefreshTokenService.java
src/main/java/com/book/backend/domain/auth/service/KakaoService.java
src/main/java/com/book/backend/domain/book/controller/BookController.java
src/main/java/com/book/backend/domain/book/service/BookService.java
src/main/java/com/book/backend/domain/detail/controller/DetailController.java
src/main/java/com/book/backend/domain/detail/service/DetailService.java
src/main/java/com/book/backend/domain/genre/controller/GenreController.java
src/main/java/com/book/backend/domain/genre/service/GenreService.java
src/main/java/com/book/backend/domain/library/controller/LibraryController.java
src/main/java/com/book/backend/domain/openapi/service/RequestValidate.java
src/main/java/com/book/backend/domain/opentalk/controller/OpentalkController.java
src/main/java/com/book/backend/domain/opentalk/service/OpentalkService.java
src/main/java/com/book/backend/domain/search/controller/SearchController.java
src/main/java/com/book/backend/domain/search/service/SearchService.java
src/main/java/com/book/backend/domain/user/controller/UserController.java
src/main/java/com/book/backend/domain/user/service/UserService.java
src/main/java/com/book/backend/domain/userBook/controller/UserBookController.java
src/main/java/com/book/backend/domain/userBook/service/UserBookService.java
src/main/java/com/book/backend/global/ResponseTemplate.java
src/main/java/com/book/backend/global/log/LogBackConfig.java
src/main/resources/application.yml

**로그 및 swagger docs 가독성 있게 수정**
- ### Log
- ### Swagger
> 앞으로 새로운 contoller.java 파일 생성할 때, @Tag 어노테이션만 추가하면 됩니다!

#90 refactor log

---

src/main/java/com/book/backend/domain/auth/service/AuthService.java
src/main/java/com/book/backend/domain/auth/service/KakaoService.java
src/main/java/com/book/backend/domain/user/service/UserService.java
src/main/java/com/book/backend/exception/ErrorCode.java

#93 fix decoding

---

src/main/java/com/book/backend/domain/auth/controller/AuthController.java
src/main/java/com/book/backend/domain/auth/service/AppleService.java
src/main/java/com/book/backend/domain/auth/service/AuthService.java
src/main/java/com/book/backend/domain/auth/service/KakaoService.java
src/main/java/com/book/backend/domain/user/entity/User.java
src/main/java/com/book/backend/domain/user/repository/UserRepository.java
src/main/java/com/book/backend/domain/user/service/UserService.java
src/main/java/com/book/backend/exception/ErrorCode.java

#98 fix user

---

src/main/java/com/book/backend/domain/message/controller/MessageController.java
src/main/java/com/book/backend/domain/message/dto/MessageRequestDto.java
src/main/java/com/book/backend/domain/message/service/MessageService.java
src/main/java/com/book/backend/domain/opentalk/controller/OpentalkController.java
src/main/java/com/book/backend/domain/opentalk/service/OpentalkService.java
src/main/java/com/book/backend/domain/userOpentalk/repository/UserOpentalkRepository.java
src/main/java/com/book/backend/exception/ErrorCode.java

#102 favorite opentalk

---

src/main/java/com/book/backend/domain/opentalk/controller/OpentalkController.java
src/main/java/com/book/backend/domain/opentalk/dto/OpentalkDto.java
src/main/java/com/book/backend/domain/opentalk/dto/OpentalkJoinResponseDto.java
src/main/java/com/book/backend/domain/opentalk/service/OpentalkResponseParser.java
src/main/java/com/book/backend/domain/opentalk/service/OpentalkService.java

[feat] #107 오픈톡 참여하기 api 에 즐찾 여부 추가

---

src/main/java/com/book/backend/domain/user/entity/User.java

[fix] 회원탈퇴 API 오류 해결

---

src/main/java/com/book/backend/domain/detail/controller/DetailController.java
src/main/java/com/book/backend/domain/openapi/dto/response/DetailResponseDto.java
src/main/java/com/book/backend/domain/opentalk/service/OpentalkService.java
src/main/java/com/book/backend/domain/userBook/service/UserBookService.java
src/main/java/com/book/backend/exception/ErrorCode.java
src/main/java/com/book/backend/global/SwaggerConfig.java
src/main/resources/application.yml

#111 8/25 수정사항

---

src/main/java/com/book/backend/domain/openapi/service/ResponseParser.java

[feat] ResponseParser에 중복 방지 로직 추가

---

src/main/java/com/book/backend/domain/goal/controller/GoalController.java
src/main/java/com/book/backend/domain/goal/dto/MyProgressDto.java
src/main/java/com/book/backend/domain/goal/dto/UserProgressDto.java
src/main/java/com/book/backend/domain/goal/mapper/GoalMapper.java
src/main/java/com/book/backend/domain/goal/service/GoalService.java

#131 fix goal api

---

src/main/java/com/book/backend/global/JwtAuthenticationFilter.java

> 메서드 추출 및 조건문 분리 등의 리팩토링 전략을 활용하여 JWT 인증 필터링 로직을 리팩토링했습니다.
> 기존 코드의 기능은 그대로 유지했습니다!

#142 JWT 인증 필터링 로직 리팩토링

---

src/main/java/com/book/backend/domain/oidc/OidcProviderFactory.java
src/main/java/com/book/backend/domain/oidc/apple/AppleAuthClient.java
src/main/java/com/book/backend/domain/oidc/kakao/KakaoAuthClient.java

> 기존 OIDC 처리 코드에 `@RequiredArgsConstructor`를 사용하지 않고 작성된 코드가 있어, 가독성을 위해 해당 코드들을 리팩토링했습니다.

#145 [refactor] OIDC 생성자 할당 로직 리팩토링

---

src/main/java/com/book/backend/domain/oidc/OidcProviderFactory.java
src/main/java/com/book/backend/domain/oidc/apple/AppleAuthClient.java
src/main/java/com/book/backend/domain/oidc/kakao/KakaoAuthClient.java

Reverts BOOK-TALK/Readables-Server#148

Revert "#145 [refactor] OIDC 생성자 할당 로직 리팩토링"
